# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Deploy static or Python app directly without zipping

name: Deploy Static or Python App to Azure Web App - stock-alert-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Optional Python environment setup (keep if you plan to expand with Python)
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Skip zip creation, deploy the repository root directly
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7E46074B64A8493E8C8DF280799529F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7907CD62BC764697BDE3D43653678553 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2F430DBF0AB64D628FE6502130D8ABD5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'stock-alert-site'
          slot-name: 'Production'
          package: '.'
